# -*- coding: utf-8 -*-
"""pythonpractise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Za-V_HjnebpH3JozvuNvoFW_XvSWmCQ

**Basic Python**
## ***FOR MINIPROJECTS SCROLL DOWN***
"""

name = 'Adam'
hobby = 'coding'
occupation = 'Programmer'
country = 'Greece'
print('Hello , my name is', name,'and', 'i live in', country)
print('I also love',hobby, 'in my free time')
print(102*45)
print(name)
print(hobby)

name = 'Adam'
color = 'red'
print('My favorite colour is', color)

name=input('What is your occupation?')
print(name)

name=input('What is your name?')
age=input('What is your age?')
print('Nice to meet you',name )
city=input('Where do you live')
print(city,age)

age=input('How old are you?')
age=int(age)
if age >= 80:
  print('Free entrance')
elif age >= 50:
  print('Ticket cost 40$')
else:
  print('Ticket cost 60$')

name=input('What is your name?')
age=int(input('How old are you'))

if age >= 18:
  print('Welcome,', name, ',you can enter')
else:
  print('Sorry mr/ms', name, 'you cannot enter')

for i in range(10):
    print(i)
for(i) in range(3):
    print('Hi, my name is Adam')
for i in range(3):
    print('This is line number', i)


name=input('What is your name')

for i in range(2):
    print('Hello,', name,'!')

"""**FUNCTIONS**"""

def greet():
  print('Hello, welcome to my python practise project')
greet()

def greet(name):
  print('hello,', name, 'welcome to my pythn practise project')
greet('Adam')
greet('Mary')
greet('Johnys')



def math(a,b,c):
  result = a + b + c
  print(a,'+', b, '+', c, '=', result)
math(1,2,3)
math(146,8903,432121)

def print_card(name, age, color):
  print('------')
  print('Name:', name)
  print('Age:', age)
  if age >= 18:
    print('Status: Adult')
  else:
    print('Status: Minor')
  print('Favourite colour:', color)
  print('------')
name = input('What is your name ? ')
age = int(input('What is your age ? '))
color = input('What is your favourite colour? ')
print_card(name, age, color)

def print_card2(name, age, color):
 print('------')
 print('Name:', name)
 print('Age:', age)
 if age >= 18:
  print('Status: Adult')
 else:
  print('Status: Minor')
 print('------')
name=input('What is your name ? ')
age=int(input('What is your age ? '))
color=input('What is your favourite colour?')
print_card2(name, age, color)

for i in range(3):
  print('Person', i + 1)
  name=input('What is your name ? ')
  age=int(input('What is your age ?'))
  color=input('What is your favourite colour ? ')
  print_card(name, age, colour)

"""# **LISTS**"""

fruits=['banana', 'apple', 'cherry']
print(fruits)

numbers=[1,2,3,4,5,6,7,8,9,0]
print(numbers)

food=['burger', 'pizza', 'gyros']
print(food)
print(food[0])
print(food[2])
print(food[-1])
print('My favourite food is', food[0])


food.append('Meat')
print(food)
food.remove('Meat')
print(food)

shopping_list=[]
shopping_list.append('milk')
shopping_list.append('eggs')
print('My list:', shopping_list)

shopping_list.remove('milk')
print('New list:', shopping_list)

food=['burger', 'pizza']

for food in food:
  print('I like', food)

for food in food:
  if food == 'burger':
    print('not pass')
  else:
    print('pass')

"""# **Mini project: Shopping list App

"""

shopping=[]


for i in range(5):
  item=input('Add an item to your shopping  list ')
  shopping.append(item)

print('\n Your shopping list:')
for item in shopping:
  print('-', item)

remove=input('\n Which item do you want to remove ? ')
shopping.remove(item)

print('\n Updated list:')
for item in shopping:
  print('-', item)

"""# **Dictionaries**"""

pc={
    'cpu' : 'intel', 'gpu' : 'amd', 'storage' : 'sandisk', 'ram' : '32gb'
    }
print(pc['cpu'])
print(pc['storage'])
print('Cpu manufacturer is', pc['cpu'])
print('My pc has', pc['ram'], 'ram')


pc['PSU']='Corsair'
pc['COOLING']='Noctua'
pc['gpu']='Nvdia'
print(pc['gpu'])
print(pc)

new_dict={}
new_dict['name']=input('What is your name ? ')
new_dict['age']=input('What is your age ? ')
new_dict['country']=input('Where do you live ?')
print(new_dict)

person={'name' : 'Adam', 'age' : 50 }
for k, ve in person.items():
  print(k, ':', ve)

scores={'adam' : 40, 'mary' : 30, 'stef' : 80}
for name,score in scores.items():
  if score >= 50:
    print(name, 'got an A')
  else:
    print(name,'got a B')

"""# **Mini Project #2**"""

contacts=[]

def add_contacts():
  contact={}
  contact['Name']=input('Name: ')
  contact['phone']=input('Phone: ')
  contact['email']=input('Email : ')
  contacts.append(contact)
  print('Contact added!\n')

def show_contacts():
  print('----Your Contacts---')
  for contact in contacts:
    for k,v in contact.items():
      print(k, ':', v)
    print('----------------')